### ISSUE TITLE
Clean up Start functionality in Scene object

### ISSUE THREAD

**Issue by kmfarley11** [Triangle345/GT#14]
Right now calling Start() on a scene renders image after image with no concern for input handling. This makes Windows very upset. 

The Start Scene functionality should be cleaned up so that we can handle basic termination more elegantly (i.e. Ctrl+C or the Close button). 

While in there, also enforce a 1ms wait time (to start) in order to allow the images to fully load etc. View the effects of this on various platforms and decide a good amount of wait time in between iterations.

Finally, make Update and Draw to be private methods. We want the user to run Start but not to manually draw.

**Comment by kmfarley11** [comment]
I implemented the issue such that we can elegantly exit when closing the window or hitting Escape (see the above commit). 

I am not sure if CtrlC should be handled the same way since this will eventually be utilized in the form of actual games. Escape will likely need to be handled differently as well, but this can be enhanced with issue #9.

I also noticed that the "Delta" is not really being used at all. I implemented appropriate arithmetical logic for it; however, I left a comment based on the concern that it is currently serving no purpose.

Finally, I can make Draw easily private but Update is trickier. Since the Update function is defined in Nodes but used in Scene, it would be a bit trickier to implement it as a private function. Not sure how to handle this protected-type situation in Go but I could do more research later if we still want that.

Let me know if you have any input on this.

**Comment by Triangle345** [comment]
so I actually think we can remove the scene interface all together for now.. we really do not use it or handle many scenes (no 3d yet).

The delta gets used normally by the users while implementing movement e.g: x = x + movement_speed \* delta

So i think we should maybe make ALL of node and component update and initialize methods in the interface private.

**Comment by kmfarley11** [comment]
I was starting to question the reason for using the scene interface as well. All it really is, is a middle man for drawing the Nodes. But at the same time it does abstract some useful functionality.

Not sure what would be best, just depends on how we want to do it. I think getting rid of the scene and using Node operations may free up the engine to be more modular (no middle man). But this could also potentially sacrifice some simplicity for the end user.

I'm good with either decision, just let me know the verdict (or we could discuss more) and one of us can implement it.

And another note about the delta. I understand that it could be useful for someone to use, I am merely stating that we are doing absolutely nothing with it. We aren't even storing it anywhere. We are merely passing it to the Node update function which re-curses yet does nothing with it / puts it nowhere. We should store it somewhere if we ever plan to make use of it (possibly in the Node?).

**Comment by Triangle345** [comment]
Right we need a scene however the interface right now is not needed. The scene handles node functionality. It draws and clears and in the future will set perspective and culling..

We could store delta globally in some timing structure and allow user to call that when needed. However that structure will be empty as I'm not sure what else we can put in there, that's why I had delta in update... update would be the only one really using it anyways once a user implements it

**Comment by kmfarley11** [comment]
After further discussion it has been decided to remove the Scene Interface and to enact fps limiting + delta storage. However, the limiting / delta handling will be done in a separate issue.
