### ISSUE TITLE
golang gl in ubuntu needs symlink to gl lib

### ISSUE THREAD

**Issue by Triangle345** [Triangle345/GT#15]
So in Ubuntu (or what ever other OS's) may contain libGL (from mesa-dev) in specific lib architecture folders. In order to compile golang gl you will need to symlink those to /usr/lib like so:

```
ln -s /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 /usr/lib/libGL.so
```

**Comment by kmfarley11** [comment]
Is this the only way? I am surprised that this isn't already done when installing mesa-dev.

If we need to do this then we should probably prepare a simple script and update the installation procedure to reflect this. I do not currently have an Ubuntu system available and thus will not enact it.

**Comment by Triangle345** [comment]
yea i ran this on ubuntu 16.04. This kind of relates to the other issue of creating a "project creator" app that helps out with this and even provides templates, at least until we create the editor.

Did it run on yours just installing generic mesa dev?

**Comment by kmfarley11** [comment]
With the recent switch to 300 es (shaders) I was able to just straight up run what we had. My dpkg reports that I have mesa-common-dev and mesa-utils installed (on a debian 64 VM).

For reference, a full list of my dpkg --list | grep mesa:
ii  libegl1-mesa:amd64
ii  libegl1-mesa-dev:amd64
ii  libegl1-mesa-drivers:amd64
ii  libgl1-mesa-dev:amd64
ii  libgl1-mesa-dri:amd64
ii  libgl1-mesa-glx:amd64
ii  libglapi-mesa:amd64
ii  libgles2-mesa:amd64
ii  libgles2-mesa-dev:amd64
ii  libglu1-mesa:amd64
ii  libglu1-mesa-dev
ii  libopenvg1-mesa:amd64
ii  libwayland-egl1-mesa:amd64
ii  mesa-common-dev:amd64

**Comment by Triangle345** [comment]
yea with this "install app" if we make it, it would package everything locally so you just install our game engine and run it, done. No external deps.

**Comment by kmfarley11** [comment]
Are you referencing issue #2 when you talk of this install app? If so then we can probably just migrate the necessary information from here and close this issue. 

Unless this is not fixed (in Ubuntu) via simple packaging: A simple test should be run to see whether a symlink is absolutely necessary, and whether installing a package (i.e. mesa-common-dev) properly fixes it. If a package installation fixes it then I propose we close / migrate this issue.

**Comment by Triangle345** [comment]
#2 need to merge with this. Create new project app tool
