### ISSUE TITLE
crash during appending of textures

### ISSUE THREAD

**Issue by Triangle345** [Triangle345/GT#22]
when loading two or more fonts in (about 5k pixel x length) , engine crashes.  after further investigation it was determined that appendImage was concatenating the length twice. This huge length exceeded the max texture size on my intel hd 520 (8k max size).

**Comment by Triangle345** [comment]
Will implement binary buddy for searching through the aggregate image and assigning free space to make the best use of all the precious real estate.

**Comment by Triangle345** [comment]
I guess next step is to use the BuddyAggretator [https://github.com/Triangle345/GT/blob/master/Graphics/Image/BuddyAggregator.go#L165](url)

to hold images - the correct way :)

**Comment by kmfarley11** [comment]
Is this fixed? If so we should close the issue

**Comment by Triangle345** [comment]
Fixed
