### ISSUE TITLE
need to create 2d animation helper framework/classes/etc

### ISSUE THREAD

**Issue by Triangle345** [Triangle345/GT#3]
2d currently can display sprites but needs to be a lot easier with animation and timing , etc.

**Comment by Triangle345** [comment]
Some features to possibly add:

Animation actions. Stop, Start
Animation Initialization: Repeatable animation or no?

**Comment by kmfarley11** [comment]
At the moment, Animation is mostly functional via the SpriteAnimation class and SpriteRenderer Component. The next step will be to get input handling, scripting, and animation to handshake with each other. Before doing that though, I will try to abstract the Animation functionality (index tracking and frequency setting etc.) into a more general interface for use with both the SpriteRenderer and ModelRenderer classes.

**Comment by kmfarley11** [comment]
I firmly believe in the use of the SpriteAnimation class and its separation from the SpriteRenderer. It works well and seems very logical to me:

___Renderer does the drawing and contains a map of animations from which the user can add / select (i.e. renderer.SetCurrentAnimation("left_animation"))

___Animation holds a list of items to be rendered and gives the user configuration visibility over timing and content of the animation in question. Many methods (but not all) inside here are interfaced 

AnimationHelper.go provides functionality universal to the Animation classes (currently only has update logic). The Animation interface is also listed in here

Note: at this point, 3d animation should be able to recycle most of what is in SpriteAnimation.go and use the Animation interface to render a list of 3d models.

**Comment by kmfarley11** [comment]
We have changed the gl render logic so that we no longer need to interface the animation work. Instead we have a common AnimationManager but separate renderers.

With the most recent commit, i feel that this particular issue has been met and propose we close it

**Comment by kmfarley11** [comment]
This issue seems to be implemented, if any bugs or features are related then open a new issue.
